### PR TITLE
Logcontrol re-integration

### LINKED ISSUE #506: polkit crashes when the LogTarget D-Bus property is set
**Describe the bug**
```sh
$ busctl set-property org.freedesktop.PolicyKit1 /org/freedesktop/LogControl1 org.freedesktop.LogControl1 LogTarget "s" ''
Failed to set property LogTarget on interface org.freedesktop.LogControl1: Remote peer disconnected
```
```
#0  0x00007f11e1a80724 in __pthread_kill_implementation () from target:/lib64/libc.so.6
#1  0x00007f11e1a27d0e in raise () from target:/lib64/libc.so.6
#2  0x00007f11e1a0f942 in abort () from target:/lib64/libc.so.6
#3  0x00007f11e24e414c in g_assertion_message[cold] () from target:/lib64/libglib-2.0.so.0
#4  0x00007f11e25538c7 in g_assertion_message_expr () from target:/lib64/libglib-2.0.so.0
#5  0x00007f11e270887d in invoke_set_property_in_idle_cb () from target:/lib64/libgio-2.0.so.0
#6  0x00007f11e2527add in g_idle_dispatch () from target:/lib64/libglib-2.0.so.0
#7  0x00007f11e252128c in g_main_context_dispatch_unlocked.lto_priv () from target:/lib64/libglib-2.0.so.0
#8  0x00007f11e25817f8 in g_main_context_iterate_unlocked.isra () from target:/lib64/libglib-2.0.so.0
#9  0x00007f11e2527377 in g_main_loop_run () from target:/lib64/libglib-2.0.so.0
#10 0x0000000000403a32 in main (argc=<optimized out>, argv=<optimized out>) at ../src/polkitbackend/polkitd.c:294
```
**To Reproduce**
```sh
busctl set-property org.freedesktop.PolicyKit1 /org/freedesktop/LogControl1 org.freedesktop.LogControl1 LogTarget "s" ''
```
It can also be triggered by just running dfuzzer (FYI @mrc0mmand)

**Expected behavior**
It shouldn't crash.

Looks like it's from 79d84d0dd0dd7d16c616555acf8cd14862d02baf

### PR DESCRIPTION
**Pull request by jrybar-rh**
## Summary
[short description of the problem and the change]: #
Re-commit of https://github.com/polkit-org/polkit/commit/79d84d0dd0dd7d16c616555acf8cd14862d02baf with additional authorization check.

## Detailed description and/or reproducer
[Please be more descriptive yet concise here. This text will help us with testing, urgency and severity assessment.]: #
Setting log level via dbus api is now restricted to root only and setting log target is disabled completely.
Fixes #506 and #507

### CODE REVIEW

File: src/polkitbackend/polkitbackendauthority.c [hunk 1]
```diff
@@ -1349,22 +1364,125 @@ server_handle_get_property (GDBusConnection  *connection,
...
+  if ((uid_t)polkit_unix_user_get_uid (caller_user) != 0)
+    {
+      g_set_error (error, G_IO_ERROR, G_IO_ERROR_PERMISSION_DENIED, "Only root can change the log level");
+      g_object_unref (caller_user);
+      g_object_unref (caller_subject);
+      return FALSE;
+    }
+
+  g_variant_get (value, "&s", &level);
+  polkit_backend_authority_set_log_level (level);
```
Comment (evverx) [inline src/polkitbackend/polkitbackendauthority.c:1480]: I think error handling is missing here in the sense that it accepts anything without returning errors. For example here's what `systemd-resolved` does:
```sh
# busctl set-property org.freedesktop.resolve1 /org/freedesktop/LogControl1 org.freedesktop.LogControl1 LogLevel "s" yolo
Failed to set property LogLevel on interface org.freedesktop.LogControl1: Invalid log level 'yolo'
# echo $?
1
```
Here's what polkit does:
```sh
# busctl set-property org.freedesktop.PolicyKit1 /org/freedesktop/LogControl1 org.freedesktop.LogControl1 LogLevel "s" yolo
# echo $?
0
```

Comment (evverx) [reply src/polkitbackend/polkitbackendauthority.c:1480]: @jrybar-rh since it's still half-implemented should a new issue be opened to at least document how it interacts with `--no-debug` or is it going to be added to https://github.com/polkit-org/polkit/pull/425 (or any other PR) later?

Comment (jrybar-rh) [reply src/polkitbackend/polkitbackendauthority.c:1480]: Or send pull request.

Comment (evverx) [reply src/polkitbackend/polkitbackendauthority.c:1480]: Fair enough. I'll collect all the shortcomings and try to document them (though I'm not a native English speaker so I'm not the best person to write the documentation)
